#!/bin/bash
set -e

# pCloud Upload Pipeline - Installer
# Installs the dashboard, staging watcher, and upload watcher

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="/etc/pcloud-pipeline.env"

echo "========================================="
echo "  pCloud Upload Pipeline v2.0 - Install"
echo "========================================="
echo

# --- Preflight checks ---
check_cmd() {
    if ! command -v "$1" &>/dev/null; then
        echo "ERROR: $1 is not installed."
        echo "  Install it with: $2"
        exit 1
    fi
}

check_cmd docker "https://docs.docker.com/engine/install/"
check_cmd rclone "curl https://rclone.org/install.sh | sudo bash"
check_cmd sqlite3 "apt install sqlite3"

if ! docker compose version &>/dev/null; then
    echo "ERROR: docker compose plugin is not installed."
    echo "  Install it with: apt install docker-compose-plugin"
    exit 1
fi

# Check rclone has at least one remote
if [ -z "$(rclone listremotes 2>/dev/null)" ]; then
    echo "ERROR: No rclone remotes configured."
    echo "  Run: rclone config"
    echo "  Set up your pCloud (or other cloud) remote first."
    exit 1
fi

echo "All prerequisites found."
echo

# --- Gather configuration ---
read -rp "Pipeline base path [/opt/pcloud-pipeline/data]: " PIPELINE_BASE
PIPELINE_BASE="${PIPELINE_BASE:-/opt/pcloud-pipeline/data}"

echo
echo "Browse paths: directories the dashboard file browser can access."
echo "Enter comma-separated paths (e.g. /data/media,/data/downloads)"
read -rp "Browse paths [${PIPELINE_BASE}]: " BROWSE_PATHS_INPUT
BROWSE_PATHS_INPUT="${BROWSE_PATHS_INPUT:-${PIPELINE_BASE}}"

read -rp "Dashboard password [pcloud123]: " DASHBOARD_PASSWORD
DASHBOARD_PASSWORD="${DASHBOARD_PASSWORD:-pcloud123}"

echo
echo "Available rclone remotes:"
rclone listremotes
echo
read -rp "rclone remote + path (e.g. pcloud:/Auto-Uploads): " RCLONE_REMOTE
if [ -z "$RCLONE_REMOTE" ]; then
    echo "ERROR: rclone remote is required."
    exit 1
fi

read -rp "Dashboard port [5001]: " DASHBOARD_PORT
DASHBOARD_PORT="${DASHBOARD_PORT:-5001}"

read -rp "Timezone [$(cat /etc/timezone 2>/dev/null || echo UTC)]: " TZ
TZ="${TZ:-$(cat /etc/timezone 2>/dev/null || echo UTC)}"

echo
echo "--- Configuration Summary ---"
echo "  Pipeline base:    $PIPELINE_BASE"
echo "  Browse paths:     $BROWSE_PATHS_INPUT"
echo "  Dashboard pass:   $DASHBOARD_PASSWORD"
echo "  rclone remote:    $RCLONE_REMOTE"
echo "  Dashboard port:   $DASHBOARD_PORT"
echo "  Timezone:         $TZ"
echo "-----------------------------"
echo
read -rp "Proceed with installation? [Y/n]: " CONFIRM
if [[ "$CONFIRM" =~ ^[Nn] ]]; then
    echo "Aborted."
    exit 0
fi

# --- Install system dependencies ---
echo
echo "[1/6] Installing system dependencies..."
apt-get update -qq
apt-get install -y -qq inotify-tools sqlite3 lsof > /dev/null

# --- Create directories ---
echo "[2/6] Creating pipeline directories..."
mkdir -p "$PIPELINE_BASE"/{staging,uploads,failed,.temp,logs,backups}

# --- Create SQLite database ---
if [ ! -f "$PIPELINE_BASE/transfers.db" ]; then
    echo "[2/6] Initializing database..."
    sqlite3 "$PIPELINE_BASE/transfers.db" <<'SQL'
CREATE TABLE IF NOT EXISTS transfers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    source_path TEXT NOT NULL,
    dest_path TEXT NOT NULL,
    operation TEXT NOT NULL,
    state TEXT NOT NULL,
    size_bytes INTEGER,
    progress INTEGER DEFAULT 0,
    error TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
PRAGMA journal_mode=WAL;
SQL
fi

# --- Write environment file ---
echo "[3/6] Writing config to $ENV_FILE..."
SECRET_KEY=$(python3 -c "import os; print(os.urandom(24).hex())" 2>/dev/null || openssl rand -hex 24)

cat > "$ENV_FILE" <<ENVEOF
# pCloud Upload Pipeline Configuration
# Generated by install.sh on $(date)
PIPELINE_BASE=$PIPELINE_BASE
RCLONE_REMOTE=$RCLONE_REMOTE
ALLOWED_PATHS=$BROWSE_PATHS_INPUT
DASHBOARD_PASSWORD=$DASHBOARD_PASSWORD
DASHBOARD_PORT=$DASHBOARD_PORT
SECRET_KEY=$SECRET_KEY
TZ=$TZ
PUID=$(id -u)
PGID=$(id -g)
ENVEOF

chmod 600 "$ENV_FILE"

# --- Install scripts ---
echo "[4/6] Installing watcher scripts..."
cp "$SCRIPT_DIR/scripts/pcloud-staging-watcher.sh" /usr/local/bin/
cp "$SCRIPT_DIR/scripts/pcloud-upload-watcher.sh" /usr/local/bin/
chmod +x /usr/local/bin/pcloud-staging-watcher.sh
chmod +x /usr/local/bin/pcloud-upload-watcher.sh

# --- Install systemd services ---
echo "[5/6] Installing systemd services..."
cp "$SCRIPT_DIR/systemd/pcloud-staging-watcher.service" /etc/systemd/system/
cp "$SCRIPT_DIR/systemd/pcloud-upload-watcher.service" /etc/systemd/system/
systemctl daemon-reload
systemctl enable pcloud-staging-watcher pcloud-upload-watcher
systemctl start pcloud-staging-watcher pcloud-upload-watcher

# --- Deploy dashboard ---
echo "[6/6] Deploying dashboard..."

# Create .env for docker compose
INSTALL_DIR="${SCRIPT_DIR}"
cat > "$INSTALL_DIR/.env" <<DENVEOF
PIPELINE_BASE=$PIPELINE_BASE
ALLOWED_PATHS=$BROWSE_PATHS_INPUT
DASHBOARD_PASSWORD=$DASHBOARD_PASSWORD
DASHBOARD_PORT=$DASHBOARD_PORT
SECRET_KEY=$SECRET_KEY
TZ=$TZ
PUID=$(id -u)
PGID=$(id -g)
DENVEOF

# Generate docker-compose.yml with browse path volumes
IFS=',' read -ra BPATHS <<< "$BROWSE_PATHS_INPUT"
# Build the ALLOWED_PATHS for inside the container
CONTAINER_ALLOWED=""
VOLUME_LINES=""
for bp in "${BPATHS[@]}"; do
    bp=$(echo "$bp" | xargs)  # trim whitespace
    basename=$(basename "$bp")
    container_path="/data/$basename"
    VOLUME_LINES+="      - ${bp}:${container_path}:ro\n"
    if [ -z "$CONTAINER_ALLOWED" ]; then
        CONTAINER_ALLOWED="$container_path"
    else
        CONTAINER_ALLOWED="$CONTAINER_ALLOWED,$container_path"
    fi
done
# Add pipeline base to allowed paths
CONTAINER_ALLOWED="/data/pipeline,$CONTAINER_ALLOWED"

cat > "$INSTALL_DIR/docker-compose.yml" <<COMPEOF
services:
  pcloud-dashboard:
    build: ./docker
    container_name: pcloud-dashboard
    restart: unless-stopped
    ports:
      - "${DASHBOARD_PORT}:5001"
    environment:
      - PYTHONUNBUFFERED=1
      - PIPELINE_BASE=/data/pipeline
      - ALLOWED_PATHS=${CONTAINER_ALLOWED}
      - DASHBOARD_PASSWORD=${DASHBOARD_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - TZ=${TZ}
    volumes:
      - ${PIPELINE_BASE}:/data/pipeline
      - /etc/localtime:/etc/localtime:ro
$(echo -e "$VOLUME_LINES")
COMPEOF

cd "$INSTALL_DIR"
docker compose build --quiet
docker compose up -d

echo
echo "========================================="
echo "  Installation Complete!"
echo "========================================="
echo
echo "  Dashboard:  http://$(hostname -I | awk '{print $1}'):${DASHBOARD_PORT}"
echo "  Password:   $DASHBOARD_PASSWORD"
echo "  Config:     $ENV_FILE"
echo "  Data:       $PIPELINE_BASE"
echo
echo "  Services:"
echo "    systemctl status pcloud-staging-watcher"
echo "    systemctl status pcloud-upload-watcher"
echo "    docker logs pcloud-dashboard"
echo
echo "  To uninstall: $SCRIPT_DIR/uninstall.sh"
echo "========================================="
